Repository geldata/gel, pull requests merged in 2020-01, with the labels that each got.

#1057 Fix rendering of datetimes
  edb/repl/render_binary.py
Labels: high priority

#1058 Change SET ANNOTATION to CREATE/ALTER ANNOTATION
  docs/edgeql/ddl/aliases.rst
  docs/edgeql/ddl/annotations.rst
  docs/edgeql/ddl/constraints.rst
  docs/edgeql/ddl/functions.rst
  docs/edgeql/ddl/indexes.rst
  docs/edgeql/ddl/links.rst
  docs/edgeql/ddl/objects.rst
  docs/edgeql/ddl/props.rst
  docs/edgeql/ddl/scalars.rst
  edb/edgeql/ast.py
  edb/edgeql/codegen.py
  edb/edgeql/parser/grammar/ddl.py
  edb/lib/_testmode.edgeql
  edb/lib/cfg.edgeql
  edb/pgsql/datasources/schema/annos.py
  edb/pgsql/intromech.py
  edb/schema/annos.py
  edb/schema/ordering.py
  tests/test_edgeql_ddl.py
  tests/test_edgeql_syntax.py
  tests/test_edgeql_userddl.py
  tests/test_schema.py
  tests/test_server_proto.py
  tests/test_type_coverage.py
Labels: edgeql

#1071 Add args to the server for automatic temp cluster bootstrap
  edb/server/buildmeta.py
  edb/server/cluster.py
  edb/server/daemon/daemon.py
  edb/server/main.py
  edb/server/mng_port/edgecon.pxd
  edb/server/mng_port/edgecon.pyx
  edb/server/mng_port/port.py
  edb/server/pgcluster.py
  edb/server/server.py
  tests/test_server_ops.py
  tests/test_type_coverage.py
Labels: DO NOT MERGE

#1096 Add type annotations for schema name and expr modules
  edb/schema/expr.py
  edb/schema/name.py
  edb/schema/types.py
  mypy.ini
  tests/test_type_coverage.py
Labels: code-quality

#1153 tests: Adjust some test to check `decimal` exact value.
  docs/clients/90_edgeql/protocol.rst
  docs/clients/99_graphql/protocol.rst
  docs/datamodel/scalars/numeric.rst
  edb/testbase/server.py
  tests/test_edgeql_functions.py
Labels: needs-backport

#1155 docs: Fix broken links.
  docs/admin/setup.rst
Labels: bug, documentation, needs-backport

#1165 docs: Add multiple inheritance description.
  docs/datamodel/index.rst
  docs/datamodel/objects.rst
  docs/edgeql/overview.rst
  docs/edgeql/sdl/objects.rst
Labels: needs-backport
