Repository geldata/gel, pull requests merged in 2023-10, with the labels that each got.

#6177 Document for conditional DML workaround
  docs/edgeql/for.rst
  docs/stdlib/set.rst
Labels: documentation

#6228 Show how to determine the outcome of upsert
  docs/edgeql/insert.rst
Labels: documentation

#6236 Document missing environment variables
  docs/reference/environment.rst
Labels: documentation

#6286 Add big scary warning about custom IDs
  docs/stdlib/cfg.rst
Labels: documentation

#6290 Fix type name injection on computed backlinks without a shape
  edb/edgeql/compiler/schemactx.py
  tests/test_edgeql_select.py
Labels: backport, 3.0, 4.0

#6297 Fix use of UNLESS CONFLICT in triggers
  edb/edgeql/compiler/normalization.py
  edb/edgeql/tracer.py
  tests/test_schema.py
Labels: backport-4.x, backport-3.x

#6301 Fix cardinality inference around delegated exclusive constraints
  edb/edgeql/compiler/inference/cardinality.py
  edb/schema/pointers.py
  tests/schemas/cards_ir_inference.esdl
  tests/test_edgeql_ir_card_inference.py
Labels: backport-4.x

#6303 Fix query_compilation metrics
  edb/server/dbview/dbview.pyx
  edb/server/metrics.py
  edb/server/protocol/binary.pyx
  edb/server/protocol/execute.pyi
  edb/server/protocol/execute.pyx
  edb/server/protocol/system_api.py
Labels: backport-4.x

#6313 Fix uuid->object casts in access policies in nested INSERTs
  edb/pgsql/compiler/context.py
  tests/test_edgeql_insert.py
Labels: backport-4.x, backport-3.x

#6314 Make 'reference to a non-existent schema item <id>' an ISE
  edb/schema/schema.py
Labels: backport-4.x, backport-3.x

#6329 Tweak parser recovery to prefer SELECT over INSERT
  edb/edgeql-parser/src/parser.rs
  edb/tools/parser_demo.py
  tests/test_edgeql_syntax.py
Labels: backport-4.x

#6328 Add a special param token for normalization
  edb/edgeql-parser/edgeql-parser-python/src/normalize.rs
  edb/edgeql-parser/edgeql-parser-python/tests/normalize.rs
  edb/edgeql-parser/src/parser.rs
  edb/edgeql-parser/src/tokenizer.rs
  edb/edgeql-parser/src/validation.rs
  edb/edgeql-parser/tests/tokenizer.rs
  edb/edgeql/parser/grammar/commondl.py
  edb/edgeql/parser/grammar/expressions.py
  edb/edgeql/parser/grammar/tokens.py
  tests/test_edgeql_syntax.py
Labels: backport-4.x

#6330 Fix GA dryrun workflow
  .github/workflows.src/build.inc.yml
  .github/workflows/dryrun.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
Labels: backport-4.x, backport-3.x

#6324 Add ext::auth email verification
  edb/server/protocol/auth_ext/config.py
  edb/server/protocol/auth_ext/email.py
  edb/server/protocol/auth_ext/errors.py
  edb/server/protocol/auth_ext/http.py
  edb/server/protocol/auth_ext/local.py
  edb/server/protocol/auth_ext/ui.py
  tests/test_http_ext_auth.py
  tests/test_server_ops.py
Labels: backport-4.x

#6346 Fix coalesce with DML in non-dev builds
  edb/edgeql/compiler/expr.py
  edb/edgeql/compiler/options.py
  edb/edgeql/compiler/stmt.py
  edb/server/compiler/compiler.py
  tests/test_edgeql_insert.py
Labels: backport-4.x

#6351 Use consistent kebab-case for auth URLs
  edb/server/protocol/auth_ext/http.py
  edb/server/protocol/auth_ext/ui.py
  tests/test_http_ext_auth.py
Labels: backport-4.x

#6352 Support auth for HTTP endpoints
  edb/buildmeta.py
  edb/lib/cfg.edgeql
  edb/server/args.py
  edb/server/protocol/auth_helpers.pxd
  edb/server/protocol/auth_helpers.pyx
  edb/server/protocol/binary.pyx
  edb/server/protocol/execute.pyx
  edb/server/protocol/frontend.pyx
  edb/server/protocol/protocol.pyx
  edb/server/server.py
  edb/testbase/http.py
  edb/testbase/server.py
  setup.py
  tests/test_http_edgeql.py
  tests/test_http_graphql_query.py
  tests/test_http_notebook.py
  tests/test_server_auth.py
  tests/test_server_proto.py
Labels: backport-4.x

#6362 Avoid pickling schemas on _every_ DDL statement when restoring a dump
  edb/server/compiler/compiler.py
Labels: backport-4.x, backport-3.x

#6357 Change adaptive pool scale-up condition
  edb/server/compiler_pool/pool.py
  tests/test_server_compiler.py
Labels: backport-4.x

#6366 Move script entrypoints from `setup.py` to `pyproject.toml`
  pyproject.toml
  setup.py
Labels: backport-4.x, backport-3.x

#6369 Make ext::auth::ClientTokenIdentity single
  edb/edgeql/compiler/expr.py
  tests/test_http_ext_auth.py
Labels: backport-4.x

#6367 Don't cache UI assets in memory when the Admin UI is disabled
  edb/server/protocol/ui_ext.pyx
  edb/server/server.py
Labels: backport-4.x

#6377 Include auth_ext static assets in the package build
  MANIFEST.in
  tests/test_http_ext_auth.py
Labels: backport-4.x

#6379 Add a hack to make migration deadlocks less likely in some common cases
  edb/pgsql/delta.py
  tests/test_edgeql_ddl.py
Labels: backport-4.x, backport-3.x

#6381 Support globals-using functions in defaults
  edb/edgeql/compiler/setgen.py
  tests/test_edgeql_ddl.py
Labels: backport-4.x, backport-3.x

#6375 Make parser spec generation deterministic
  edb/common/parsing.py
  edb/edgeql-parser/src/parser.rs
  edb/edgeql/parser/__init__.py
  edb/tools/parser_demo.py
  tests/test_edgeql_syntax.py
Labels: backport-4.x

#6382 Recompile functions when globals/aliases/computeds change
  edb/schema/delta.py
  edb/schema/expraliases.py
  edb/schema/functions.py
  edb/schema/inheriting.py
  edb/schema/objtypes.py
  edb/schema/pointers.py
  tests/test_edgeql_ddl.py
  tests/test_schema.py
Labels: backport-4.x, backport-3.x

#6385 Allow `if .. then .. else` at the top level
  edb/edgeql/codegen.py
  edb/edgeql/parser/grammar/expressions.py
  edb/edgeql/parser/grammar/start.py
  tests/test_edgeql_expressions.py
  tests/test_edgeql_syntax.py
Labels: backport-4.x

#6383 Provide an error message for failed PKCE verification
  edb/server/protocol/auth_ext/errors.py
  edb/server/protocol/auth_ext/http.py
Labels: backport-4.x

#6396 Require PKCE in password reset flow
  edb/server/protocol/auth_ext/http.py
  edb/server/protocol/auth_ext/ui.py
  tests/test_http_ext_auth.py
Labels: backport-4.x

#6399 Make parallel test runner report errors that happen in teardown
  edb/tools/test/runner.py
Labels: backport-4.x, backport-3.x

#6402 Cap the size of sets in the config system
  edb/server/config/ops.py
  tests/test_server_config.py
Labels: backport-4.x
