Repository geldata/gel, pull requests merged in 2024-04, with the labels that each got.

#7139 Fix two bugs affecting unions in computed links
  edb/edgeql/tracer.py
  edb/schema/ddl.py
  tests/test_schema.py
Labels: backport-4.x, backport-3.x, backport-5.x

#7143 Fix two GROUP bugs involving USING clauses
  edb/edgeql/desugar_group.py
  tests/test_edgeql_group.py
Labels: backport-4.x, backport-3.x, backport-5.x

#7158 Add cfg::Config._query_cache_mode
  edb/buildmeta.py
  edb/common/debug.py
  edb/lib/cfg.edgeql
  edb/server/compiler/compiler.py
  edb/server/config/__init__.py
  edb/server/config/types.py
  edb/server/dbview/dbview.pyx
  edb/server/tenant.py
Labels: backport-5.x

#7187 Accept session changes in transactions
  edb/server/compiler/compiler.py
  tests/test_protocol.py
Labels: backport-4.x, backport-5.x

#7197 Fix patch system bug when doing a config patch of an extension
  edb/server/server.py
Labels: backport-4.x, backport-3.x, backport-5.x

#7201 Fix another patch system extension problem
  edb/server/server.py
Labels: backport-4.x, backport-3.x, backport-5.x

#7203 Fix deserialization of persistent cache entries after upgrade
  .github/scripts/patches/create-databases.py
  edb/server/compiler/rpc.pyx
Labels: backport-5.x

#7199 Consider database __default__ for SQL connections
  edb/server/protocol/pg_ext.pyx
Labels: backport-5.x

#7200 pg_ext: don't yield NoData in SimpleQuery
  edb/server/pgcon/pgcon.pyx
  tests/test_pgext.py
Labels: backport-3.x, backport-5.x

#7226 Stop the AI extension task when a branch is dropped
  edb/server/dbview/dbview.pyx
Labels: backport-5.x

#7227 Fix dropping AI indexes in a parent and child at the same time
  edb/pgsql/delta.py
  edb/pgsql/delta_ext_ai.py
  edb/schema/indexes.py
  tests/test_edgeql_data_migration.py
Labels: backport-5.x

#7230 Fix AI columns to not appear in SQL introspection tables
  edb/buildmeta.py
  edb/pgsql/metaschema.py
  edb/schema/sources.py
  tests/test_sql_query.py
Labels: backport-5.x

#7225 Fix restoring dumps that use ai extension
  edb/pgsql/delta_ext_ai.py
  edb/server/compiler/compiler.py
  tests/schemas/dump_v5_default.esdl
  tests/schemas/dump_v5_setup.edgeql
  tests/test_dump_v5.py
Labels: backport-5.x

#7235 Include fts and ai shadow index columns in dumps
  edb/pgsql/delta.py
  edb/server/compiler/compiler.py
Labels: backport-5.x

#7242 Make ai::search have integrated sort and hit indexes
  edb/pgsql/compiler/relgen.py
  tests/schemas/ext_ai.esdl
  tests/test_edgeql_data_migration.py
  tests/test_ext_ai.py
Labels: backport-5.x

#7252 Tweak parser so it does not skip semicolons
  edb/edgeql-parser/src/parser.rs
  tests/test_schema_syntax.py
Labels: backport-5.x

#7251 Force return cast on range get upper and lower functions.
  edb/buildmeta.py
  edb/lib/std/31-rangefuncs.edgeql
  tests/test_edgeql_expressions.py
Labels: backport-5.x

#7254 Bump shmmax on macos x86 and limit the tests we run
  .github/workflows.src/build.inc.yml
  .github/workflows/dryrun.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
Labels: backport-5.x

#7262 Prevent dump hangups from leaving stray postgres queries
  edb/server/protocol/binary.pyx
  edb/server/protocol/frontend.pyx
Labels: to-backport-5.x

#7271 Don't inject exclusive conflict checks for updates without children
  edb/edgeql/compiler/conflicts.py
Labels: to-backport-5.x

#7267 Switch EDGEDB_DEBUG_EDGEQL_TEXT_IN_SQL to encode string as json
  edb/server/compiler/compiler.py
Labels: to-backport-5.x

#7272 Fix doing a no-op update to an exclusive multi pointer with children
  edb/pgsql/deltadbops.py
  edb/pgsql/schemamech.py
  tests/schemas/constraints.esdl
  tests/test_constraints.py
Labels: to-backport-5.x

#7281 Fix regression in using some tuple literals as a default
  edb/pgsql/schemamech.py
  tests/test_edgeql_ddl.py
Labels: to-backport-5.x

#7279 Fix constraint handling when pointer has cardinality or computedness changed
  edb/pgsql/dbops/constraints.py
  edb/pgsql/delta.py
  edb/pgsql/deltadbops.py
  tests/test_edgeql_ddl.py
Labels: to-backport-5.x
