Repository geldata/gel, pull requests merged in 2024-03, with the labels that each got.

#6942 Allow passing WebAuthn user_handle in request body
  edb/server/protocol/auth_ext/http.py
  edb/server/protocol/auth_ext/webauthn.py
  tests/test_http_ext_auth.py
Labels: backport-5.x

#6954 Move extension tests to their own file
  tests/test_edgeql_ddl.py
  tests/test_edgeql_extensions.py
Labels: backport-5.x

#6945 Handle WebAuthn challenge having multiple factors
  edb/lib/ext/auth.edgeql
  edb/server/protocol/auth_ext/data.py
  edb/server/protocol/auth_ext/webauthn.py
  tests/test_http_ext_auth.py
Labels: backport-5.x

#6981 Support CONFIGURE CURRENT BRANCH
  edb/edgeql/parser/grammar/config.py
  edb/edgeql/parser/grammar/statements.py
  edb/edgeql/qltypes.py
  tests/test_edgeql_extensions.py
  tests/test_edgeql_syntax.py
  tests/test_server_config.py
Labels: backport-5.x

#6349 Lock concurrent compiles of the same query
  edb/server/dbview/dbview.pxd
  edb/server/dbview/dbview.pyx
  edb/server/server.py
Labels: backport-5.x

#6974 Return JSON for magic link register
  edb/server/protocol/auth_ext/http.py
  tests/test_http_ext_auth.py
Labels: auth, backport-5.x

#6990 Schema version in query cache key
  edb/server/compiler/rpc.pxd
  edb/server/compiler/rpc.pyi
  edb/server/compiler/rpc.pyx
  edb/server/dbview/dbview.pxd
  edb/server/dbview/dbview.pyx
  edb/server/protocol/binary.pyx
  edb/server/protocol/execute.pyx
  tests/test_server_compiler.py
Labels: backport-5.x

#6996 Support new default branch behavior
  edb/server/args.py
  edb/server/bootstrap.py
  edb/server/defines.py
  edb/server/protocol/binary.pyx
  edb/server/protocol/protocol.pyx
  edb/server/protocol/system_api.py
  edb/server/tenant.py
  edb/testbase/server.py
  tests/test_backend_connect.py
  tests/test_server_auth.py
  tests/test_server_config.py
  tests/test_server_ops.py
Labels: backport-5.x

#6984 Add a cfg::BranchConfig alias for cfg::DatabaseConfig
  edb/buildmeta.py
  edb/edgeql/compiler/schemactx.py
  edb/lib/cfg.edgeql
  edb/schema/expraliases.py
  edb/schema/types.py
  tests/test_server_config.py
Labels: backport-5.x

#6967 Change grouping element to use trailing commas.
  edb/edgeql/parser/grammar/expressions.py
  tests/test_edgeql_syntax.py
Labels: backport-5.x

#6999 Fix computed single scalar globals
  edb/pgsql/compiler/relctx.py
  tests/test_edgeql_globals.py
Labels: backport-4.x, backport-5.x

#7001 Add a `std::get_current_branch()` function
  edb/buildmeta.py
  edb/lib/sys.edgeql
  tests/test_database.py
Labels: backport-5.x

#7002 [5.x] Allow grouping to have trailing comma.
  edb/edgeql/parser/grammar/expressions.py
  tests/test_edgeql_syntax.py
Labels: backport-4.x, backport-3.x

#6987 Ensure WebAuthn redirect matches expected shape
  edb/server/protocol/auth_ext/_static/webauthn-authenticate.js
  edb/server/protocol/auth_ext/_static/webauthn-register.js
Labels: backport-5.x

#6959 Split recompile and writeback in transaction
  edb/server/compiler/rpc.pyx
  edb/server/dbview/dbview.pxd
  edb/server/dbview/dbview.pyx
  edb/server/protocol/binary.pyx
  edb/server/protocol/execute.pyx
Labels: backport-5.x

#6460 Add mTLS support
  edb/server/args.py
  edb/server/main.py
  edb/server/multitenant.py
  edb/server/protocol/auth_helpers.pxd
  edb/server/protocol/auth_helpers.pyx
  edb/server/protocol/binary.pxd
  edb/server/protocol/binary.pyx
  edb/server/protocol/frontend.pyx
  edb/server/protocol/protocol.pxd
  edb/server/protocol/protocol.pyx
  edb/server/server.py
  edb/testbase/server.py
  tests/test_http_auth.py
  tests/test_server_auth.py
  tests/test_server_ops.py
Labels: backport-5.x

#7005 Enable more ruff lints
  edb/common/markup/renderers/terminal.py
  edb/common/parametric.py
  edb/edgeql/compiler/inference/cardinality.py
  edb/edgeql/compiler/schemactx.py
  edb/edgeql/compiler/setgen.py
  edb/edgeql/parser/grammar/ddl.py
  edb/edgeql/parser/grammar/expressions.py
  edb/graphql/translator.py
  edb/pgsql/compiler/relgen.py
  edb/pgsql/delta.py
  edb/schema/pointers.py
  edb/schema/reflection/structure.py
  edb/schema/scalars.py
  edb/server/compiler/compiler.py
  edb/server/compiler_pool/server.py
  edb/server/main.py
  edb/server/pgcluster.py
  edb/server/protocol/auth_ext/ui/__init__.py
  edb/server/protocol/auth_ext/ui/components.py
  edb/testbase/http.py
  edb/testbase/server.py
  edb/tools/profiling/profiler.py
  edb/tools/test/results.py
  pyproject.toml
  tests/test_backend_connect.py
  tests/test_docs.py
  tests/test_dump_v4.py
  tests/test_edgeql_data_migration.py
  tests/test_edgeql_ddl.py
  tests/test_edgeql_extensions.py
  tests/test_edgeql_for.py
  tests/test_edgeql_update.py
  tests/test_http_auth.py
  tests/test_http_ext_auth.py
  tests/test_pgext.py
  tests/test_schema.py
  tests/test_server_compiler.py
  tests/test_server_ops.py
  tests/test_sourcecode.py
Labels: backport-5.x

#6447 Add more metrics
  docs/reference/http.rst
  edb/common/prometheus.py
  edb/graphql/extension.pyx
  edb/server/dbview/dbview.pxd
  edb/server/dbview/dbview.pyx
  edb/server/metrics.py
  edb/server/pgcon/pgcon.pyx
  edb/server/protocol/auth_ext/http.py
  edb/server/protocol/binary.pyx
  edb/server/protocol/execute.pyx
  edb/server/protocol/frontend.pxd
  edb/server/protocol/frontend.pyx
  edb/server/protocol/pg_ext.pyx
  edb/server/protocol/protocol.pxd
  edb/server/protocol/protocol.pyx
Labels: backport-5.x

#7022 Add "branch" to database does not exist error message
  edb/server/dbview/dbview.pyx
Labels: backport-5.x

#7024 Serve /metrics by tenant
  edb/common/prometheus.py
  edb/server/protocol/metrics.py
  edb/server/protocol/protocol.pyx
Labels: backport-5.x

#7033 Inject tenant in all* logging records
  edb/common/log.py
  edb/server/logsetup.py
  edb/server/main.py
  edb/server/multitenant.py
  edb/server/protocol/pg_ext.pyx
  edb/server/protocol/protocol.pyx
  edb/server/server.py
  edb/server/tenant.py
Labels: backport-5.x

#7034 Fallback to PKCE RFC parameter names
  docs/guides/auth/built_in_ui.rst
  docs/guides/auth/email_password.rst
  docs/guides/auth/oauth.rst
  edb/server/protocol/auth_ext/http.py
  tests/test_http_ext_auth.py
Labels: backport-5.x

#7037 Add optional PKCE challenge in email verification
  edb/server/protocol/auth_ext/http.py
  tests/test_http_ext_auth.py
Labels: backport-4.x, backport-5.x

#7025 Do persistent cache writebacks asynchronously
  Makefile
  edb/common/asyncutil.py
  edb/common/debug.py
  edb/server/compiler/compiler.py
  edb/server/compiler/dbstate.py
  edb/server/dbview/dbview.pxd
  edb/server/dbview/dbview.pyx
  edb/server/pgcon/pgcon.pyx
  edb/server/protocol/binary.pyx
  edb/server/protocol/execute.pyx
  edb/server/tenant.py
  pyproject.toml
  tests/common/test_asyncutil.py
Labels: backport-5.x

#7041 Fix edb server development mode logging
  edb/tools/edb.py
Labels: backport-5.x

#7036 Add __setstate__ method to handle Expression consistency when unpickling
  edb/schema/expr.py
Labels: backport-5.x

#7044 Improve error when applying a shape to a parameter
  edb/edgeql/compiler/astutils.py
  edb/edgeql/compiler/stmtctx.py
  tests/test_edgeql_select.py
  tests/test_server_proto.py
Labels: backport-5.x

#7055 Prevent parser from repeating unexpected errors
  edb/edgeql-parser/src/parser.rs
Labels: backport-5.x

#7047 Optimize pickled in-tx CompilerConnectionState
  edb/server/compiler/dbstate.py
  edb/server/compiler_pool/multitenant_worker.py
  edb/server/compiler_pool/pool.py
  edb/server/compiler_pool/queue.py
  edb/server/compiler_pool/server.py
  edb/server/compiler_pool/worker.py
  edb/server/dbview/dbview.pxd
  edb/server/dbview/dbview.pyx
  tests/test_server_compiler.py
Labels: backport-4.x, backport-5.x

#7062 Fix issues with cached global shapes and global cardinality inference
  edb/edgeql/compiler/expr.py
  edb/ir/ast.py
  edb/pgsql/compiler/relctx.py
  tests/schemas/cards_ir_inference.esdl
  tests/test_edgeql_ddl.py
  tests/test_edgeql_ir_card_inference.py
Labels: backport-5.x

#7065 Add error when a constant set is used in singleton mode
  edb/pgsql/compiler/expr.py
  tests/test_constraints.py
Labels: backport-5.x

#7073 Fix update rewrites on types that are children of updated type
  edb/edgeql/compiler/viewgen.py
  tests/test_edgeql_rewrites.py
Labels: backport-4.x, backport-5.x

#7076 Parser recovery: prevent suggesting ADMINISTER
  edb/edgeql-parser/src/parser.rs
  tests/test_edgeql_syntax.py
Labels: backport-4.x, backport-5.x

#7087 Set "Connection: close" for non-keep-alive requests
  edb/server/protocol/protocol.pyx
Labels: backport-4.x, backport-5.x

#7106 Fix fts::search volatility
  edb/lib/fts.edgeql
Labels: backport-5.x

#6956 Alter alias even from ref propagation
  edb/schema/delta.py
  edb/schema/expraliases.py
  edb/schema/inheriting.py
  edb/schema/reflection/writer.py
Labels: backport-5.x
