Repository geldata/gel, pull requests merged in 2024-12, with the labels that each got.

#8060 Fix schema ordering issue with Trigger when clauses
  edb/edgeql/declarative.py
  tests/test_schema.py
Labels: to-backport-5.x

#8070 Add test for previously fixed implicit limit bug
  tests/test_edgeql_for.py
Labels: to-backport-5.x

#8078 Fix config bugs with env vars and default checking
  edb/ir/staeval.py
  edb/server/main.py
  tests/test_server_config.py
Labels: to-backport-4.x, to-backport-5.x

#8127 Wait for all webhook requests
  tests/test_http_ext_auth.py
Labels: to-backport-6.x

#8129 Send `identity_id` on require_verification
  edb/server/protocol/auth_ext/http.py
Labels: to-backport-6.x

#8131 Improve connection setting value parsing over SQL adapter
  edb/cli/.gitignore
  edb/server/compiler/sql.py
  edb/server/protocol/pg_ext.pyx
  setup.py
  tests/test_sql_query.py
Labels: to-backport-6.x

#8140 Fix psql "\d table" by making casting to regclass more resilient
  edb/pgsql/resolver/static.py
  edb/testbase/server.py
  tests/test_sql_query.py
Labels: to-backport-6.x

#8145 Change some pg_catalog views to be MATERIALIZED
  edb/buildmeta.py
  edb/pgsql/dbops/views.py
  edb/pgsql/metaschema.py
  edb/server/compiler/ddl.py
Labels: to-backport-6.x

#8149 Some followups to MATERIALIZED pg_catalog views
  edb/pgsql/metaschema.py
  edb/server/bootstrap.py
Labels: to-backport-6.x

#8148 test: try to fix QueryStats test to be more reliable
  tests/test_edgeql_sys.py
Labels: to-backport-6.x

#8151 pg-ext: fix initial client_encoding
  edb/server/pgcon/pgcon.pyx
  edb/server/protocol/pg_ext.pyx
  tests/test_sql_query.py
Labels: to-backport-6.x
