Repository geldata/gel, pull requests merged in 2024-01, with the labels that each got.

#6629 Docs: Fix auth guide links and note
  docs/guides/auth/email_password.rst
  docs/guides/auth/index.rst
  docs/guides/auth/oauth.rst
Labels: documentation

#6659 Document `EDGEDB_DEBUG_HTTP_INJECT_CORS`
  docs/reference/environment.rst
Labels: documentation

#6683 Docs: Remove Pydantic warning from FastAPI guide
  docs/guides/tutorials/rest_apis_with_fastapi.rst
Labels: documentation

#6665 Speed up introspection of system objects like Database and Role
  edb/pgsql/compiler/clauses.py
  edb/pgsql/compiler/context.py
  edb/pgsql/compiler/relctx.py
  edb/schema/reflection/structure.py
  edb/server/bootstrap.py
Labels: backport-4.x

#6706 Fix issue with schema changes when trigger depends on a rewrite
  edb/schema/rewrites.py
  tests/test_edgeql_ddl.py
Labels: backport-4.x, backport-3.x

#6723 Get verification data from request body
  edb/server/protocol/auth_ext/http.py
  tests/test_http_ext_auth.py
Labels: backport-4.x

#6718 Make overloading a link when omitting link keyword work
  edb/schema/unknown_pointers.py
  tests/test_schema.py
Labels: backport-4.x

#6747 Fix issues with empty sets leaking out of optional scopes
  edb/pgsql/compiler/relctx.py
  edb/pgsql/compiler/relgen.py
  tests/test_edgeql_scope.py
Labels: backport-4.x, backport-3.x
