Repository geldata/gel, pull requests merged in 2025-08, with the labels that each got.

#8919 auth: add email header and fix alt content bug
  edb/server/protocol/auth_ext/ui/__init__.py
Labels: to-backport-6.x

#8932 Fix updating of two single links with linkprops at once
  edb/pgsql/compiler/dml.py
  tests/schemas/updates.esdl
  tests/test_edgeql_policies.py
  tests/test_edgeql_update.py
Labels: to-backport-6.x

#8955 Avoid duplicating a cached computed global in some unnecessary cases
  edb/edgeql/compiler/context.py
  edb/edgeql/compiler/policies.py
  edb/edgeql/compiler/setgen.py
  edb/edgeql/compiler/stmtctx.py
  tests/test_edgeql_sql_codegen.py
Labels: to-backport-7.x

#8952 auth: Add a test for client_token and ClientTokenIdentity
  tests/test_http_ext_auth.py
Labels: to-backport-7.x

#8953 Add `permission auth_read_user` for reading *just* the current Identity
  edb/buildmeta.py
  edb/lib/ext/auth.edgeql
  tests/test_http_ext_auth.py
Labels: needs-inplace-upgrade-fix, to-backport-7.x

#8961 Fix handling of SQL syntax error over gel proto
  edb/pgsql/parser/__init__.py
  edb/pgsql/parser/parser.pyx
Labels: to-backport-6.x, to-backport-7.x

#8964 Drop required_permissions on all ext::auth::_jwt_* functions
  edb/buildmeta.py
  edb/lib/ext/auth.edgeql
Labels: needs-inplace-upgrade-fix, to-backport-7.x

#8981 Fix referencing a computed pointer in a conversion USING expression
  edb/pgsql/delta.py
  tests/test_edgeql_ddl.py
Labels: to-backport-6.x, to-backport-7.x

#8975 Work around for bug #8974 when updating extension globals using secrets
  edb/edgeql/compiler/setgen.py
  edb/schema/types.py
Labels: backported-7.x

#8991 Enable FOR OPTIONAL
  edb/edgeql/compiler/stmt.py
  tests/test_edgeql_for.py
Labels: to-backport-7.x

#8994 Don't lose overlays when iterating over DML with FOR
  edb/ir/utils.py
  edb/pgsql/compiler/clauses.py
  edb/pgsql/compiler/context.py
  edb/pgsql/compiler/relctx.py
  edb/pgsql/compiler/relgen.py
  tests/test_edgeql_insert.py
Labels: to-backport-6.x, to-backport-7.x
