Repository geldata/gel, pull requests merged in 2025-02, with the labels that each got.

#8288 Fix inline functions substituting parameters from hidden nodes.
  edb/common/ast/transformer.py
  edb/edgeql/compiler/func.py
  tests/test_edgeql_functions_inline.py
Labels: to-backport-6.x

#8294 Fix broken error messages for type mismatches in a number of schema objects
  edb/schema/functions.py
  edb/schema/policies.py
  edb/schema/triggers.py
  tests/test_edgeql_ddl.py
  tests/test_edgeql_triggers.py
Labels: to-backport-6.x

#8298 Add `pg_show_all_settings` to allowed pg functions
  edb/pgsql/resolver/static.py
  tests/test_sql_query.py
Labels: to-backport-5.x, to-backport-6.x

#8292 Mark the assert_* functions as being Immutable
  edb/buildmeta.py
  edb/lib/std/20-genericfuncs.edgeql
Labels: to-backport-6.x

#8304 Fix schema_repair() more fully
  edb/server/compiler/ddl.py
Labels: to-backport-6.x

#8307 Get rid of some import cycle fragility that breaks LSP
  edb/schema/unknown_pointers.py
Labels: to-backport-6.x

#8311 setup: Skip UI when building the language server
  setup.py
Labels: to-backport-6.x

#8316 Don't emit instance configs matching their defaults in DESCRIBE INSTANCE CONFIG
  edb/edgeql/compiler/config_desc.py
  tests/test_server_config.py
Labels: to-backport-6.x

#8315 [sql] Fix non-normalized queries over native protocol
  edb/edgeql/tokenizer.py
  edb/pgsql/parser/parser.pyx
  edb/pgsql/resolver/static.py
  edb/server/compiler/compiler.py
  edb/server/compiler/dbstate.py
  edb/server/compiler/sql.py
  edb/server/dbview/dbview.pyx
  tests/test_sql_query.py
Labels: to-backport-6.x

#8317 Also retry on transaction serialization errors
  edb/testbase/connection.py
Labels: backported-6.x

#8318 Handle session state sync properly with tx-behavior settings
  edb/server/dbview/dbview.pxd
  edb/server/dbview/dbview.pyx
  edb/server/pgcon/pgcon.pxd
  edb/server/pgcon/pgcon.pyx
  edb/server/protocol/execute.pyx
  edb/server/protocol/pg_ext.pxd
  edb/server/protocol/pg_ext.pyx
  tests/test_server_proto.py
Labels: to-backport-6.x

#8320 Use sys_pgcon for long-term advisory locks
  edb/server/protocol/ai_ext.py
Labels: to-backport-6.x

#8321 Fix pg_catalog types over native SQL
  .gitignore
  edb/server/dbview/dbview.pxd
  edb/server/dbview/dbview.pyx
  tests/test_sql_query.py
Labels: to-backport-6.x

#8324 Switch to building as Gel
  .github/workflows.src/build.inc.yml
  .github/workflows/dryrun.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
Labels: to-backport-6.x

#8322 Increase number of retries to 10 in test connection
  edb/testbase/connection.py
Labels: to-backport-6.x

#8323 Make the PKCE gc loop use RepeatableRead
  edb/server/protocol/auth_ext/pkce.py
Labels: to-backport-6.x

#8327 Drop tx isolation of interal queries in ext::ai to RepeatableRead
  edb/server/pgcon/pgcon.pyi
  edb/server/pgcon/pgcon.pyx
  edb/server/protocol/ai_ext.py
Labels: to-backport-6.x

#8328 Drop bionic support
  .github/workflows.src/build.targets.yml
  .github/workflows/dryrun.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
Labels: to-backport-5.x, to-backport-6.x

#8331 Publish to Docker Hub as geldata/gel
  .github/workflows.src/build.inc.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
Labels: to-backport-6.x

#8332 Implement caching for JWKSet
  Cargo.lock
  Cargo.toml
  edb/server/_rust_native/Cargo.toml
  edb/server/_rust_native/src/lib.rs
  edb/server/http.py
  edb/server/protocol/auth_ext/base.py
  edb/server/tenant.py
  pyproject.toml
  rust/gel-http/Cargo.toml
  rust/gel-http/src/cache.rs
  rust/gel-http/src/lib.rs
  rust/gel-http/src/python.rs
  tests/test_http.py
  tests/test_http_ext_auth.py
Labels: to-backport-6.x

#8335 Expose `administer statistics_update()`
  docs/reference/admin/index.rst
  docs/reference/admin/statistics_update.rst
  docs/reference/admin/vacuum.rst
  edb/server/compiler/compiler.py
  edb/server/compiler/ddl.py
Labels: to-backport-6.x

#8334 Revert "Also retry on transaction serialization errors (#8317)"
  edb/testbase/connection.py
Labels: to-backport-6.x

#8338 Skip SQL cache in cache recompilation
  edb/server/dbview/dbview.pyx
  tests/test_server_ops.py
Labels: to-backport-6.x

#8339 bug fix: auto_rebuild_query_cache gate was broken
  edb/server/config/__init__.py
  edb/server/dbview/dbview.pyx
  tests/test_server_ops.py
Labels: to-backport-6.x

#8342 Report the number of times a feature is used as a metric
  edb/server/compiler/ddl.py
  edb/server/dbview/dbview.pyx
  edb/server/metrics.py
Labels: to-backport-6.x

#8354 Make \(name)-style string interpolation work for errmessage
  edb/schema/constraints.py
  edb/schema/delta.py
  edb/schema/objects.py
  edb/schema/utils.py
  tests/test_constraints.py
Labels: to-backport-6.x

#8364 Fix FILTER clause MANY warning when FILTER body is a literal set of bools
  edb/edgeql/compiler/expr.py
Labels: to-backport-6.x

#8369 Report migration count and object count as metrics
  edb/server/compiler/ddl.py
Labels: to-backport-6.x

#8379 Increase recursion limit in compiler worker processes
  edb/edgeql/compiler/config_desc.py
  edb/server/compiler_pool/worker_proc.py
  tests/test_edgeql_userddl.py
Labels: to-backport-6.x

#8394 Fix referencing ext::auth::ClientTokenIdentity from a link default
  edb/pgsql/schemamech.py
  tests/test_edgeql_ddl.py
  tests/test_http_ext_auth.py
Labels: to-backport-6.x

#8371 Fix tagging SQL over binary protocol
  edb/server/dbview/dbview.pyx
  edb/server/protocol/binary.pyx
  edb/testbase/connection.py
  tests/test_edgeql_sys.py
Labels: to-backport-6.x

#8406 Add default value for ai::EmbeddingModel::embedding_model_max_batch_tokens
  docs/reference/ai/extai.rst
  edb/buildmeta.py
  edb/lib/ext/ai.edgeql
  tests/test_edgeql_data_migration.py
Labels: to-backport-6.x

#8416 Fix ai extension connecting to branch being dropped
  edb/server/protocol/ai_ext.py
Labels: to-backport-6.x

#8419 Fix `ON TARGET DELETE ALLOW` behavior when link optionality is changed
  edb/pgsql/delta.py
  tests/test_edgeql_ddl.py
Labels: to-backport-6.x
