Repository geldata/gel, pull requests merged in 2025-01, with the labels that each got.

#8166 Fix pg_constraint oid duplication
  edb/buildmeta.py
  edb/pgsql/metaschema.py
Labels: to-backport-6.x

#8159 Fix SQL introspection after inplace upgrade
  edb/server/cluster.py
  edb/server/inplace_upgrade.py
  tests/inplace-testing/test.sh
Labels: to-backport-6.x

#8172 test: use new server for stats tests
  tests/test_edgeql_sys.py
Labels: to-backport-6.x

#8174 Fix SQL settings_to_str for enums and bools
  edb/server/pgcon/pgcon.pxd
  edb/server/pgcon/pgcon.pyx
  edb/server/protocol/pg_ext.pyx
  tests/test_sql_query.py
Labels: to-backport-6.x

#8195 Allow `--extensions-dir` to specify extension sources directly
  edb/server/tenant.py
Labels: to-backport-6.x

#8121 Add TOML config file support
  edb/buildmeta.py
  edb/common/asyncutil.py
  edb/pgsql/metaschema.py
  edb/server/args.py
  edb/server/config/__init__.py
  edb/server/main.py
  edb/server/multitenant.py
  edb/server/pgcon/__init__.py
  edb/server/pgcon/connect.py
  edb/server/pgcon/pgcon.pxd
  edb/server/pgcon/pgcon.pyi
  edb/server/smtp.py
  edb/server/tenant.py
  edb/testbase/server.py
  tests/common/test_asyncutil.py
  tests/test_server_config.py
  tests/test_server_ops.py
Labels: to-backport-6.x

#8205 Fix SQL native for queries that are not simple selects
  edb/pgsql/resolver/__init__.py
  edb/server/compiler/sql.py
  tests/test_sql_query.py
Labels: to-backport-6.x

#8212 Bump rust deps to resolve security warnings
  Cargo.lock
  Cargo.toml
Labels: to-backport-6.x

#8209 Detect crashed test runners and report and exit
  edb/tools/test/mproc_fixes.py
  edb/tools/test/runner.py
Labels: to-backport-6.x

#8213 Implict limit for SQL over native (#8206)
  edb/pgsql/resolver/__init__.py
  edb/pgsql/resolver/context.py
  edb/server/compiler/compiler.py
  edb/server/compiler/sql.py
  edb/testbase/server.py
  tests/test_sql_query.py
Labels: to-backport-6.x

#8216 test: bootstrap without testmode for multitenant test
  edb/server/args.py
  edb/testbase/server.py
  tests/test_server_ops.py
Labels: backported-6.x

#8210 Implement \(expr)-style string interpolation
  edb/edgeql-parser/edgeql-parser-python/src/normalize.rs
  edb/edgeql-parser/src/helpers/strings.rs
  edb/edgeql-parser/src/parser.rs
  edb/edgeql-parser/src/tokenizer.rs
  edb/edgeql-parser/src/validation.rs
  edb/edgeql/ast.py
  edb/edgeql/codegen.py
  edb/edgeql/compiler/expr.py
  edb/edgeql/parser/grammar/expressions.py
  edb/edgeql/parser/grammar/tokens.py
  edb/edgeql/quote.py
  edb/edgeql/tracer.py
  tests/test_edgeql_expressions.py
  tests/test_edgeql_syntax.py
Labels: to-backport-6.x

#8217 Monitor open FDs
  edb/server/metrics.py
Labels: to-backport-5.x, to-backport-6.x

#8202 Add a server_notice callback during handshake
  rust/pgrust/src/errors/mod.rs
  rust/pgrust/src/handshake/client_state_machine.rs
  rust/pgrust/src/python.rs
Labels: to-backport-6.x

#8220 Try to fix test_server_ops_multi_tenant in release builds
  tests/test_server_ops.py
Labels: to-backport-6.x

#8229 multitenant: patch stdlib with testmode schema if requested
  edb/server/args.py
  edb/server/main.py
  edb/testbase/server.py
  tests/test_server_config.py
  tests/test_server_ops.py
Labels: to-backport-6.x

#8236 multitenant: retry adding tenants more eagerly
  edb/server/multitenant.py
  tests/test_server_ops.py
Labels: to-backport-5.x, to-backport-6.x

#8226 Fix a ordering based flake in test_edgeql_triggers_mixed_all_02
  tests/test_edgeql_triggers.py
Labels: to-backport-6.x

#8237 Allow dropping isolation level to REPEATABLE READ in a READ ONLY tx
  edb/edgeql-parser/src/keywords.rs
  edb/edgeql/parser/grammar/statements.py
  edb/server/compiler/compiler.py
  tests/test_server_proto.py
Labels: to-backport-4.x, to-backport-5.x, to-backport-6.x

#8235 Fix sql value functions in rel vars over SQL adapter
  edb/pgsql/codegen.py
  edb/pgsql/common.py
  edb/pgsql/resolver/range_var.py
  tests/test_sql_query.py
Labels: to-backport-6.x

#8240 Fix dump and MIGRATION REWRITE when there are many (>1000) migrations
  edb/schema/ddl.py
  edb/schema/migrations.py
  edb/server/compiler/ddl.py
  tests/test_edgeql_data_migration.py
Labels: to-backport-5.x, to-backport-6.x

#8243 Don't hardcode number of tests in test_server_ops_multi_tenant
  tests/test_server_ops.py
Labels: to-backport-5.x, to-backport-6.x

#8248 Delete old .s.EDGEDB.admin.XXX sockets
  edb/server/server.py
Labels: to-backport-6.x

#8249 Retry test suite queries after TransactionConflictError
  edb/testbase/connection.py
  tests/test_server_proto.py
Labels: to-backport-5.x, to-backport-6.x

#8251 [sql] Support inserting into column with _id suffix
  edb/pgsql/resolver/command.py
  tests/test_sql_dml.py
Labels: to-backport-6.x

#8252 [sql] Fix some bugs with UNION and similar
  edb/pgsql/codegen.py
  edb/pgsql/resolver/relation.py
  tests/test_sql_parse.py
  tests/test_sql_query.py
Labels: to-backport-6.x

#8253 Remove some lingering debug code
  edb/pgsql/dbops/functions.py
  edb/schema/objects.py
  edb/schema/reflection/writer.py
Labels: to-backport-6.x

#8255 [sql] Don't ignore HAVING clause
  edb/pgsql/ast.py
  edb/pgsql/codegen.py
  edb/pgsql/compiler/astutils.py
  edb/pgsql/parser/ast_builder.py
  edb/pgsql/resolver/relation.py
  tests/test_sql_query.py
Labels: to-backport-6.x

#8256 [sql] Fix using `distinct`+`order by` and similar in native protocol
  edb/pgsql/resolver/__init__.py
  tests/test_sql_query.py
Labels: to-backport-6.x

#8258 [sql] Support DEFAULT in INSERT more fully
  edb/pgsql/resolver/command.py
  tests/test_sql_dml.py
Labels: to-backport-6.x

#8262 Produce proper errors on SQL syntax errors on native protocol
  edb/pgsql/parser/exceptions.py
  edb/pgsql/parser/parser.pyx
  edb/server/compiler/errormech.py
  edb/server/protocol/execute.pyx
  edb/server/protocol/pg_ext.pyx
  tests/test_sql_query.py
Labels: to-backport-6.x

#8268 [sql] Fix native SQL protocol on old postgres versions
  edb/pgsql/ast.py
  edb/pgsql/resolver/__init__.py
Labels: to-backport-6.x

#8263 Use better histogram buckets
  edb/common/prometheus.py
  edb/server/metrics.py
Labels: to-backport-5.x, to-backport-6.x
