Repository geldata/gel, pull requests merged in 2025-05, with the labels that each got.

#8656 Fix user_ext patches that have multiple DDL statements
  edb/server/bootstrap.py
Labels: backported-6.x

#8638 Start invalidating evicted cache entries on other frontends
  edb/api/errors.txt
  edb/errors/__init__.py
  edb/server/compiler/errormech.py
  edb/server/compiler/rpc.pxd
  edb/server/compiler/rpc.pyx
  edb/server/dbview/dbview.pyi
  edb/server/dbview/dbview.pyx
  edb/server/pgcon/pgcon.pyx
  edb/server/protocol/binary.pyx
  edb/server/protocol/execute.pyx
  edb/server/tenant.py
Labels: to-backport-6.x

#8635 Add error when using DML in a read only transaction.
  edb/server/compiler/errormech.py
  tests/test_edgeql_delete.py
  tests/test_edgeql_functions_inline.py
  tests/test_edgeql_insert.py
  tests/test_edgeql_update.py
  tests/test_server_proto.py
Labels: to-backport-6.x

#8659 Fix the initial implementation for ollama chat completion.
  edb/server/http.py
  edb/server/protocol/ai_ext.py
Labels: to-backport-6.x

#8655 server: add more compiler pool metrics
  edb/common/prometheus.py
  edb/graphql/extension.pyx
  edb/server/args.py
  edb/server/compiler_pool/pool.py
  edb/server/compiler_pool/server.py
  edb/server/compiler_pool/state.py
  edb/server/dbview/dbview.pyx
  edb/server/metrics.py
  edb/server/protocol/notebook_ext.pyx
  edb/server/protocol/pg_ext.pyx
  edb/server/protocol/protocol.pyx
Labels: to-backport-6.x

#8663 Fix error when using computed pointer in ai index.
  edb/pgsql/delta_ext_ai.py
  tests/schemas/ext_ai.esdl
  tests/test_ext_ai.py
Labels: to-backport-6.x

#8668 Fix a bug in COPY with inheritance over SQL adapter
  edb/pgsql/resolver/command.py
  tests/test_sql_query.py
Labels: to-backport-6.x

#8666 compiler server: add envvar to click options
  edb/server/args.py
  edb/server/compiler_pool/server.py
Labels: to-backport-5.x, to-backport-6.x

#8685 Fix having unnecessary constraint triggers after restore
  edb/buildmeta.py
  edb/pgsql/deltadbops.py
  edb/pgsql/schemamech.py
  edb/server/compiler/compiler.py
  edb/server/compiler/ddl.py
  tests/test_constraints.py
Labels: to-backport-6.x, needs-inplace-upgrade-fix

#8694 Make the patch system support making tweaks to user databases
  edb/server/bootstrap.py
Labels: to-backport-6.x

#8706 Pin to click 8.1
  pyproject.toml
Labels: to-backport-6.x

#8712 Move access policy filter scope subtrees to the right part of the tree
  edb/edgeql/ast.py
  edb/edgeql/compiler/context.py
  edb/edgeql/compiler/expr.py
  edb/edgeql/compiler/policies.py
  edb/edgeql/compiler/setgen.py
  tests/test_edgeql_select.py
Labels: to-backport-6.x

#8713 Disable DML on instered objects that needed for SQL
  edb/pgsql/compiler/__init__.py
  edb/pgsql/compiler/context.py
  edb/pgsql/compiler/dml.py
  edb/pgsql/resolver/command.py
Labels: to-backport-6.x

#8721 Send `IdentityCreated` webhook for OAuth sign up
  edb/server/protocol/auth_ext/http.py
  tests/test_http_ext_auth.py
Labels: to-backport-6.x

#8728 Use provided callback URL in OAuth code exchange
  edb/server/protocol/auth_ext/http.py
  edb/server/protocol/auth_ext/jwt.py
  tests/test_http_ext_auth.py
Labels: to-backport-6.x

#8730 Fix `administer schema_repair()`
  edb/server/bootstrap.py
  edb/server/compiler/ddl.py
  tests/test_edgeql_data_migration.py
  tests/test_edgeql_ddl.py
Labels: to-backport-6.x

#8737 Fix `IN` when left hand side is a SQL NULL
  edb/pgsql/compiler/relgen.py
  tests/test_edgeql_expressions.py
Labels: to-backport-6.x

#8754 Do better multiplicity inference in nested FOR expressions
  edb/edgeql/compiler/inference/multiplicity.py
  tests/test_edgeql_ir_mult_inference.py
Labels: to-backport-6.x
